/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectorecetas;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author SeijiPons
 */
public class AltaRecetas extends javax.swing.JFrame {

    public String idReceta, numMax;
    /**
     * Creates new form AltaRecetas
     */
    public AltaRecetas() {
        initComponents();
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_receta = new javax.swing.JTextField();
        txt_porciones = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_proc = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(444, 300));
        getContentPane().setLayout(null);

        jLabel1.setText("Nombre de Receta");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(16, 30, 110, 14);

        jLabel2.setText("Porciones");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(13, 68, 70, 14);
        getContentPane().add(txt_receta);
        txt_receta.setBounds(144, 27, 280, 30);
        getContentPane().add(txt_porciones);
        txt_porciones.setBounds(144, 65, 280, 30);

        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(177, 218, 100, 23);

        jLabel3.setText("Procedimiento");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(14, 96, 90, 14);

        txt_proc.setColumns(20);
        txt_proc.setRows(5);
        jScrollPane1.setViewportView(txt_proc);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(17, 116, 410, 96);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 String receta, porciones, proc;
 receta = txt_receta.getText();
 porciones = txt_porciones.getText();
 proc=txt_proc.getText();
 
        try
        {
            ConectaBD c = new ConectaBD(1);
            int nueReceta;
            String consulta="INSERT INTO recetas(receta, porciones, procedimiento) VALUES ('"+receta+"','"+porciones+"','"+proc+"');";
            System.out.println(consulta);
            Statement sentencia = c.conexion.createStatement();
            nueReceta=sentencia.executeUpdate(consulta);
            System.out.println(consulta+"   Registrando nueva receta." + " " + receta);
            
            
                        
        }catch(SQLException ex){
            System.out.println("No se registra receta");
            ex.printStackTrace();
                    
        }
     System.out.println("Hecho");
     AltaRecetas obj = new AltaRecetas();
     
     int id= Integer.parseInt(obj.recActual());
     int por=Integer.parseInt(porciones);
     
     Rel_rec_ing obj2=new Rel_rec_ing(receta,id,por);
     
        obj2.setVisible(true);
     //Salta a Interfaz de AgregarIngredienteAReceta
     
    }//GEN-LAST:event_jButton1ActionPerformed

      private String recActual(){
        try{
            ConectaBD c=new ConectaBD(1);
            ResultSet maxReceta;
            
            String consulta="SELECT MAX(idReceta) FROM recetas";
            System.out.println(consulta);
            Statement sentencia = c.conexion.createStatement();
            maxReceta=sentencia.executeQuery(consulta);
            
            while(maxReceta.next()){
                numMax=maxReceta.getString(1);
                System.out.println(maxReceta.getString(1));
                
            }
            
        }catch(SQLException ex){
            System.out.println("No selecciona palabras aleatorias");
            ex.printStackTrace();
        }
        return numMax;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaRecetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaRecetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaRecetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaRecetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaRecetas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_porciones;
    private javax.swing.JTextArea txt_proc;
    private javax.swing.JTextField txt_receta;
    // End of variables declaration//GEN-END:variables
}
