/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectorecetas;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SeijiPons
 */
public class listaRecetas extends javax.swing.JFrame {
DefaultTableModel valoresTabla;
    /**
     * Creates new form listaRecetas
     */
    public listaRecetas() {
        initComponents();
        consultaRecetas();
    }
    
    private boolean hayIngredientes(){
        ResultSet resultadoIngredientes=null;
        try{
            ConectaBD c = new ConectaBD(2);
            ResultSetMetaData datosConsulta;
            String consulta="SELECT * FROM  `ingredientes` ";
            Statement statement=c.conexion.createStatement();
            resultadoIngredientes=statement.executeQuery(consulta);
            
            int contadorIngredientes=0;
            while(resultadoIngredientes.next()){
               contadorIngredientes++;
            }
            
            if(contadorIngredientes==0){
                System.out.println("--> No hay ingredientes");
                resultadoIngredientes=null;
            }
            
        }catch(Exception ex){
            System.out.println("No consulta productos: "+ ex.getMessage());
        }
        
        return (resultadoIngredientes!=null);
    }
    
    private void consultaRecetas(){
        try{
            ConectaBD c=new ConectaBD(1);
            ResultSet resultadoProductos;
            ResultSetMetaData datosConsulta;
            String consulta="SELECT * FROM  `recetas` ";
            Statement sentencia=c.conexion.createStatement();
            resultadoProductos=sentencia.executeQuery(consulta);
            
            
            
            datosConsulta=resultadoProductos.getMetaData();
            String[] filasConsulta=new String[datosConsulta.getColumnCount()];
            valoresTabla=(DefaultTableModel)tablaRecetas.getModel();
             
            int a,num;
                       
            
            while(resultadoProductos.next()){
               /* for (int i=0;i<filasConsulta.length;i++)
                {
                    filasConsulta[i]=resultadoProductos.getString(i+1);
                    
                }*/
                   
                    filasConsulta[0]=resultadoProductos.getString(1);
                    filasConsulta[1]=resultadoProductos.getString(2);
                    filasConsulta[2]=resultadoProductos.getString(3);
                    
                    
                  
                   valoresTabla.addRow(filasConsulta);
            }
            tablaRecetas.setModel(valoresTabla);
            
        }catch(Exception ex){
            System.out.println("No consulta productos: "+ ex.getMessage());
            ex.printStackTrace();
            
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRecetas = new javax.swing.JTable();
        butt_verReceta = new javax.swing.JButton();
        butt_nuevaReceta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaRecetas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Receta", "Porciones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaRecetas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaRecetasMouseClicked(evt);
            }
        });
        tablaRecetas.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                tablaRecetasCaretPositionChanged(evt);
            }
        });
        jScrollPane1.setViewportView(tablaRecetas);

        butt_verReceta.setText("Ver/Modificar");
        butt_verReceta.setEnabled(false);
        butt_verReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_verRecetaActionPerformed(evt);
            }
        });

        butt_nuevaReceta.setText("Nueva Receta");
        butt_nuevaReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_nuevaRecetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(butt_verReceta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                        .addComponent(butt_nuevaReceta))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butt_nuevaReceta)
                    .addComponent(butt_verReceta))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butt_verRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_verRecetaActionPerformed
        //tomar la fila seleccionada
        int num=tablaRecetas.getSelectedRow(),idInt,porc;
        String valID = tablaRecetas.getModel().getValueAt(num, 0).toString();
        idInt=Integer.parseInt(valID);
       String valName=tablaRecetas.getModel().getValueAt(num, 1).toString();
        AltaRecetas obj = new AltaRecetas();
          porc= Integer.parseInt(tablaRecetas.getModel().getValueAt(num, 2).toString());
     Rel_rec_ing obj2=new Rel_rec_ing(valName,idInt,porc);
     
        obj2.setVisible(true);
        
        
    }//GEN-LAST:event_butt_verRecetaActionPerformed

    private void butt_nuevaRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_nuevaRecetaActionPerformed
     AltaRecetas altaRecetas = new AltaRecetas();
     
     if(hayIngredientes()){
         altaRecetas.setVisible(true);
     }
     else{
         addIngredientes objAddIng = new addIngredientes();
         objAddIng.setVisible(true);
         
         JOptionPane.showMessageDialog(rootPane, "No hay ingredientes registrados. Agregue, primero, algunos ingredientes.", "No hay ingredientes", WIDTH);
     }
        
    }//GEN-LAST:event_butt_nuevaRecetaActionPerformed

    private void tablaRecetasCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tablaRecetasCaretPositionChanged
    
    }//GEN-LAST:event_tablaRecetasCaretPositionChanged

    private void tablaRecetasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaRecetasMouseClicked
 butt_verReceta.setEnabled(true);
    }//GEN-LAST:event_tablaRecetasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listaRecetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listaRecetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listaRecetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listaRecetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listaRecetas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butt_nuevaReceta;
    private javax.swing.JButton butt_verReceta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaRecetas;
    // End of variables declaration//GEN-END:variables
}
